// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbHFwU6shZJZfjeBUjJXAa9nM__z-jiOc',
    appId: '1:583377693743:web:588d2d25a23c6a92e5aada',
    messagingSenderId: '583377693743',
    projectId: 'academy-app-55345',
    authDomain: 'academy-app-55345.firebaseapp.com',
    storageBucket: 'academy-app-55345.appspot.com',
    measurementId: 'G-Z9ZR379LGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ULLQWIugzZLqBjHECA3Jo4QFL00nsuo',
    appId: '1:583377693743:android:1beed1f6d3fd2051e5aada',
    messagingSenderId: '583377693743',
    projectId: 'academy-app-55345',
    storageBucket: 'academy-app-55345.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEVqaNoXRLF9LMPNiNaQj1_PhjGz5qNPs',
    appId: '1:583377693743:ios:de4b1f9f99b9f5abe5aada',
    messagingSenderId: '583377693743',
    projectId: 'academy-app-55345',
    storageBucket: 'academy-app-55345.appspot.com',
    iosBundleId: 'com.example.academyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEVqaNoXRLF9LMPNiNaQj1_PhjGz5qNPs',
    appId: '1:583377693743:ios:de987bab936b26dce5aada',
    messagingSenderId: '583377693743',
    projectId: 'academy-app-55345',
    storageBucket: 'academy-app-55345.appspot.com',
    iosBundleId: 'com.example.academyApp.RunnerTests',
  );
}
